# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: upgrade pip

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  setup:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4.2.2
    - name: upgrade pip
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
    - name: Test with pytest
      run: |
        pytest
